-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 17:26:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema HBC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HBC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HBC` ;
USE `HBC` ;

-- -----------------------------------------------------
-- Table `HBC`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HBC`.`Usuario` (
  `ID_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  UNIQUE INDEX `ID_usuario_UNIQUE` (`ID_usuario` ASC) VISIBLE,
  PRIMARY KEY (`ID_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HBC`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HBC`.`Perfil` (
  `ID_perfil` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(45) NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `primer_apellido` VARCHAR(45) NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `ID_usuario` INT NOT NULL,
  PRIMARY KEY (`ID_perfil`),
  UNIQUE INDEX `ID_usuario_UNIQUE` (`ID_perfil` ASC) VISIBLE,
  INDEX `fk_Perfil_Usuario1_idx` (`ID_usuario` ASC) VISIBLE,
  CONSTRAINT `perfil_usaurio`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `HBC`.`Usuario` (`ID_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HBC`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HBC`.`Curso` (
  `ID_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_curso`),
  UNIQUE INDEX `ID_curso_UNIQUE` (`ID_curso` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HBC`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HBC`.`Asignatura` (
  `ID_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre_asignatura` VARCHAR(45) NULL,
  `ID_curso` INT NULL,
  PRIMARY KEY (`ID_asignatura`),
  UNIQUE INDEX `ID_asignatura_UNIQUE` (`ID_asignatura` ASC) VISIBLE,
  INDEX `asignatura_curso_idx` (`ID_curso` ASC) VISIBLE,
  CONSTRAINT `asignatura_curso`
    FOREIGN KEY (`ID_curso`)
    REFERENCES `HBC`.`Curso` (`ID_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HBC`.`Nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HBC`.`Nota` (
  `ID_nota` INT NOT NULL AUTO_INCREMENT,
  `valor_nota` INT NULL,
  `comentarios` VARCHAR(45) NULL,
  `ID_asignatura` INT NULL,
  `ID_usuario` INT NULL,
  PRIMARY KEY (`ID_nota`),
  UNIQUE INDEX `ID_nota_UNIQUE` (`ID_nota` ASC) VISIBLE,
  INDEX `nota_asignatura_idx` (`ID_asignatura` ASC) VISIBLE,
  INDEX `nota_usuario_idx` (`ID_usuario` ASC) VISIBLE,
  CONSTRAINT `nota_asignatura`
    FOREIGN KEY (`ID_asignatura`)
    REFERENCES `HBC`.`Asignatura` (`ID_asignatura`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `nota_usuario`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `HBC`.`Usuario` (`ID_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HBC`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HBC`.`matricula` (
  `ID_matricula` INT NOT NULL AUTO_INCREMENT,
  `ID_usuario` INT NULL,
  `ID_curso` INT NULL,
  PRIMARY KEY (`ID_matricula`),
  UNIQUE INDEX `ID_matricula_UNIQUE` (`ID_matricula` ASC) VISIBLE,
  INDEX `matricula_usuario_idx` (`ID_usuario` ASC) VISIBLE,
  INDEX ` matricula_curso_idx` (`ID_curso` ASC) VISIBLE,
  CONSTRAINT `matricula_usuario`
    FOREIGN KEY (`ID_usuario`)
    REFERENCES `HBC`.`Usuario` (`ID_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT ` matricula_curso`
    FOREIGN KEY (`ID_curso`)
    REFERENCES `HBC`.`Curso` (`ID_curso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
